a = input('Digite algo:')
print ('O tipo primitivo desse algo é:', type(a))
print ('O tipo primitivo possue espaços:', a.isspace())
print ('O tipo primitivo pode ser numérico:', a.isnumeric())
print ('O tipo primitico pode ser alfabético:', a.isalpha())
print ('O tipo primitivo é alfanumérico:', a.isalnum())
print ('O tipo primitivo possue letras maiusculas:', a.isupper())
print ('O tipo primitivo possue letras minusculas:', a.islower())
print ('O tipo primitivo está capitalizada:', a.istitle())